### ISSUE TITLE
Warning mixins should come before declarations

### ISSUE THREAD

**Issue by leshekk** [AirHelp/sass-lint-config-airhelp#8]
It's necessary to solve the problem of displaying warning messages.  for  `@include media`

`warning Mixins should come before declarations`

for:

```scss
.class-name {
    width: 330px; 

    @include media('<tablet') {
        width: auto;
    }
}
```
